# Generated by Django 2.2.5 on 2019-09-22 01:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20190922_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='contenido'),
        ),
    ]
