# Generated by Django 2.2.3 on 2019-08-07 02:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 2, 12, 5, 786792, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
