# Generated by Django 2.2.5 on 2019-09-22 00:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190922_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 0, 18, 39, 662669, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
